# ===============================
# SPRING PROFILES & APP CONFIG
# ===============================
spring.profiles.active=dev
spring.application.name=API_GestionUsuariosSuscripciones

# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080
server.servlet.context-path=/api

# ===============================
# LOGGING CONFIGURATION
# ===============================
logging.level.sv.edu.udb.UserSubscriptionAPI=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO

# ===============================
# SWAGGER CONFIGURATION
# ===============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.display-request-duration=true

